### ISSUE TITLE
New configuration setting: LDAP connection options

### ISSUE THREAD

**Issue by olleolleolle** [ecraft/warden-ldap#19]
In order to connect in a specific way to LDAP, we may want to send in a symbol-keyed Hash of options to `Net::LDAP.new`.

Example:

```yaml
connection_options:
  force_no_page: true
```

Harder example: with Ruby _values_

```yaml
connection_options:
  encryption:
    method: :simple_tls
    tls_options: OpenSSL::SSL::SSLContext::DEFAULT_PARAMS
```
